### ISSUE TITLE
Test kolibri-opensearch-plugin with current kolibri 0.16 beta 

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri-opensearch-plugin#3]
## Overview 
Ensure this plugin is working properly with the next to be released version 0.16 of kolibri

**Comment by radinamatic** [comment]
No issues installing and enabling the plugin in the latest asset from the 0.16 branch, URL produced a downloadable XML

<img width="961" alt="opensearch-2023-10-25_13-10-48" src="https://github.com/learningequality/kolibri-opensearch-plugin/assets/1457929/85bb8a0a-acf3-48ac-8642-adcedc889aad">

[0zhFgg9e.zip](https://github.com/learningequality/kolibri-opensearch-plugin/files/13165218/0zhFgg9e.zip)
